nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs

enableStrictSsl: true

enableScripts: false

supportedArchitectures:
  os:
    - current
  cpu:
    - current

enableTelemetry: false
